### ISSUE TITLE
Bug: Speccy doesn't catch duplicate keys

### ISSUE THREAD

**Issue by savvyintegrations** [wework/speccy#105]
Try duplicating a path in https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml and running `speccy lint`. It won't catch the duplicate key.

**Comment by philsturgeon** [comment]
There are some things speccy ignores just due to the js-yaml parser not really caring about certain things. Somebody reported that it’ll allow trailing commas in JSON 🤣

If you’d do me a favour,  could you see if this is down to js-yaml? If that’s the case we can maybe configure t to be more strict, or switch to another parser. 

—
Phil Sturgeon

**Comment by philsturgeon** [comment]
@savvyintegrations hey! I have attempted a fix at this with #108.

**Comment by savvyintegrations** [comment]
I verified it works, thank you!
