### ISSUE TITLE
lint --json-schema option does not work

### ISSUE THREAD

**Issue by bburtin** [wework/speccy#178]
## Detailed description

The command line parsing code isn't handling the `--json-schema` option.  I debugged the code a bit and saw that the Config object is empty after the call to `config.init(cmd)` on line 68 in **lint.js**.

```
$ node_modules/.bin/speccy lint -j v2api.yaml 
XXX { config: Config {} }
Usage: speccy <command>

Options:
  -V, --version                    output the version number
  -c, --config [configFile]        config file (containing JSON/YAML). See README for potential values.
  -h, --help                       output usage information

Commands:
  lint [options] <file-or-url>     ensure specs are not just valid OpenAPI, but lint against specified rules
  resolve [options] <file-or-url>  pull in external $ref files to create one mega-file
  serve [options] <file-or-url>    view specifications in beautiful human readable documentation
```

## Your environment

* Node Version: 10.10.0
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Ubuntu 18.04

**Comment by philsturgeon** [comment]
@bburtin hey there Boris. I appreciate you digging in and debugging, but this bug report is lacking some crucial information that I'll need to solve it. When you say "does not work", do you mean that you are seeing an error? If so, what is the error. Or do you mean that you expect behavior that is different from the behavior you get? 

In its most simply case, --json-schema does in fact work just fine.

![screen shot 2018-10-22 at 11 47 20 am](https://user-images.githubusercontent.com/67381/47302833-76fd9e00-d5f0-11e8-80dd-b10c77913f6e.png)

I'll need more information to establish what exactly the problem is. :) I'll reopen when we get that.

**Comment by bburtin** [comment]
I was passing `-j` before the filename, which is the usual convention with CLI tools.  The `speccy lint -h` output implies that options are supposed to come before the filename:

```
$ node_modules/.bin/speccy lint -h
Usage: lint [options] <file-or-url>
```

I tried running with `-j` after the filename, and got a weird error:

```
$ node_modules/.bin/speccy lint -s parameter-description v2api.yaml -j
undefined
```

I'll send you some more details separately.

**Comment by philsturgeon** [comment]
The ordering does not matter, commander.js will let you do things in any order. It is often documented before, but works the same after, as my screenshot has shown. 

I think you have some very messed up specs which are causing an unexpected error when run with -j, and we can fix that if you get me an example. You mentioned on slack that you are omitting the type field entirely due to the JSON Schema vs OpenAPI-flavoured JSON Schema divergence, and that doesn't sound like it's going to work. It might be whats causing the error. 

The solution to the divergence is explained here https://blog.apisyouwonthate.com/openapi-and-json-schema-divergence-part-2-52e282e06a05 

Please do get me that example specification so we can create a unit test for whatever is going on here.
