### ISSUE TITLE
What is x-miro and why is it being added to my resolved specs?

### ISSUE THREAD

**Issue by stephen-bartell** [wework/speccy#187]
I don't know if this is a bug, so it's a question.  I see `x-miro` mentioned in #28, and I see some code to exclude it here https://github.com/wework/speccy/blob/3d1cd3a71e2ffd41c737f9d654102a84f29aca07/lib/linter.js#L106-L108

On generated specs, `x-miro` is a filepath on whatever machine generated it.

I'm still not sure what it is and I'd rather filepaths on my local devbox not get leaked out in generated specs I plan on publishing

I'll take a link to read more about what x-miro, but for now what can I do about it getting added to my specs?

Node version: 8.11.2
Speccy Version: 0.8.4

One thing I do know is that it's a fantastic gif ... https://media.giphy.com/media/uasyG63aeiUq4/giphy.gif

**Comment by rockymontana** [comment]
I too find it odd to add local paths to the production yml-file.

**Comment by MikeRalphson** [comment]
Apologies, I thought I'd responded to this already.

`x-miro` is part of the fix for this issue https://github.com/Mermade/oas-kit/issues/51 in the underlying library used for `$ref`` resolution.

It preserves information about the original `$ref` which can be used by converters (such as `swagger2openapi`) and documentation tools (such as `ReDoc`) to ensure information valuable for conversion or display of schemas using `discriminator` is not lost.

In the next version of `oas-kit` creation of this annotation will be controlled by an option, and will be off by default. I'll update this issue when done.

**Comment by MikeRalphson** [comment]
@philsturgeon feel free to transfer this issue to `oas-kit` if you prefer.

**Comment by philsturgeon** [comment]
Fixed in #198
