### ISSUE TITLE
Feature: Pre-commit hook for multi-language projects

### ISSUE THREAD

**Issue by timonbimon** [wework/speccy#216]
## Detailed description & Context

Running speccy linting as a pre-commit hook is a great way to avoid that 💩enters your codebase. Unfortunately the current lint-staged setup only supports JavaScript projects. However, some people (☝) want to run speccy in projects where they don't have a package.json (e.g. a Python backend). Adding a [pre-commit](https://pre-commit.com/) hook would do the job.

## Possible implementation

Here is an example .pre-commit-hooks.yaml file for [prettier](https://prettier.io). 
https://github.com/prettier/prettier/blob/master/.pre-commit-hooks.yaml

**Comment by philsturgeon** [comment]
Hey @timonbimon. Sadly there are probably infinite ways to do this, and i dont think we need to document them all. You can add a pre commit hook using `npx speccy lint ...` which will work without a package.json so long as npx is around. Otherwise you can play with the docer version, also listed in the main README.

If you come up with some good generic instructions, could you please PR them? 

Thank you!
